### ISSUE TITLE
Pynq_Image_V2.4_for_DPU.img download

### ISSUE THREAD

**Issue by OmarEMbed** [wutianze/HydraMini#2]
Can you please provide another way to download the image because no way to register to Baidu from outside China.
Thank you

**Comment by wutianze** [comment]
Sorry, requested by Xilinx, the image is not available out of China. But I provided one guide for you to build an image, please refer to [this](https://github.com/wutianze/dnndk-pynqz2/blob/master/build-pynqz2-system.md)
